### ISSUE TITLE
Week 4 Ready for Review

### ISSUE THREAD

**Issue by qtgiebel** [qtgiebel/portfolio#1]
@pawaitemadisoncollege Sorry this is so late. I was having trouble with the implementation, and then I just lost track of it when I started week 5. 

While it is a lot to wrap your head around at first hibernate is very useful tool for implementing db access, and it helped me finally understand what abstraction actually does. 

Most of my troubles this week were deployment issues unrelated to hibernate. The only issues I had with hibernate were caused by getting too far ahead of myself and not following along with the course material.

**Comment by pawaitemadisoncollege** [comment]
There's lots of good work here @qtgiebel! It's clear that you've put a lot of time into understanding hibernate.

- [ ] Is this commented out for a reason? https://github.com/qtgiebel/portfolio/blob/38a65fc4973a81c047ebd859518e75ca2fb33522/src/test/java/com/quinngiebel/portfolio/admin/persistence/PieceDaoTest.java#L32-L41
- [ ] Be sure to check out the GenericDao in the week 5 videos and FatBike Demo project if you haven't already. It'll provide a way to abstract even further to a single dao. It feels like you were starting to head that way with the getPiecesByColumn method, so wanted to point that out if you want continue building your own. Otherwise feel free to borrow what exists already.
- [ ] Testing an insert can be made more thorough by verifying each instance variable has the proper value.  This can most easily be done by implementing an equals method in each entity. https://github.com/qtgiebel/portfolio/blob/38a65fc4973a81c047ebd859518e75ca2fb33522/src/test/java/com/quinngiebel/portfolio/admin/persistence/PieceDaoTest.java#L38-L40

**Comment by qtgiebel** [comment]
Yes @pawaitemadisoncollege. 
- [ ] That being commented out was a product of me not opening the issue before I had started working on week 5. I commented it out so it would stop giving me error messages. In your examples I believe that you created the entity on the one side of the relationship in week 4, and the many side in week 5, whereas I did the opposite. It just needed a little bit of reverse engineering. 
- [ ] David actually brought up the GenericDao in my peer review and I have implemented it since with extending classes for each entity. 
- [ ] Thanks also for the tip about the equals method, that seems like a more robust solution.
